DROP TABLE users;
DROP TABLE administrator;
DROP TABLE licitation;
DROP TABLE message;
DROP TABLE information;
DROP TABLE inbox_messages;
DROP TABLE notification;
DROP TABLE auction;
DROP TABLE person;
