version: "3"

services:
  db:
    image: db:latest
    build: ../src/db
    container_name: db
    ports:
      - "6000:5432"
  app:
    image: auction-rest-api:latest
    build: ../src/app
    container_name: auction-rest-api
    volumes:
      - "../src/app/:/app/"
    ports:
      - "8080:5000"
    depends_on:
      - db
